export function getData(){
    return   [  
    {  
       "SEQUENCE NUMBER":1,
       "OPERATIONAL SEQUENCE ":"P4828",
       "COMPONENT NUMBER":"Employee1",
       "COMPONENT NAME":"Director of IT",
       "ITEM CATEGORY":"Employee 0",
       "REVISION NUMBER":'5464',
       "QUANTITY":"4",
       "UOM":"ttd",
       "PROCUREMENT TYPE":"each",
       "UNIT COST":"6",
       "TOTAL COST":"6",
       "CURRENCY ":"us",
       "START DATE":"12/08/2018",
       "END DATE":"15/08/2018",
       "PART TYPE":"product",
       "YIELD":"5",
       "PLANNING PERCENTAGE":"56",
       "CUSTOM ATTRIBUTES ":"",

       "childs":[  
          {
            "SEQUENCE NUMBER":1.1,
            "OPERATIONAL SEQUENCE ":"P4828",
            "COMPONENT NUMBER":"Employee1",
            "COMPONENT NAME":"Director of IT",
            "ITEM CATEGORY":"Employee 0",
            "REVISION NUMBER":'',
            "QUANTITY":"",
            "UOM":"",
            "PROCUREMENT TYPE":"",
            "UNIT COST":"",
            "TOTAL COST":"",
            "CURRENCY ":"",
            "START DATE":"",
            "END DATE":"",
            "PART TYPE":"",
            "YIELD":"",
            "PLANNING PERCENTAGE":"",
            "CUSTOM ATTRIBUTES ":"",
     
          },
          {
            "SEQUENCE NUMBER":1.2,
            "OPERATIONAL SEQUENCE ":"P4828",
            "COMPONENT NUMBER":"Employee1",
            "COMPONENT NAME":"Director of IT",
            "ITEM CATEGORY":"Employee 0",
            "REVISION NUMBER":'5464',
            "QUANTITY":"4",
            "UOM":"ttd",
            "PROCUREMENT TYPE":"each",
            "UNIT COST":"6",
            "TOTAL COST":"6",
            "CURRENCY ":"us",
            "START DATE":"12/08/2018",
            "END DATE":"15/08/2018",
            "PART TYPE":"product",
            "YIELD":"5",
            "PLANNING PERCENTAGE":"56",
            "CUSTOM ATTRIBUTES ":"",
          }
         ]
        
    },
    {
      "SEQUENCE NUMBER":2,
      "OPERATIONAL SEQUENCE ":"P4828",
      "COMPONENT NUMBER":"Employee1",
      "COMPONENT NAME":"Director of IT",
      "ITEM CATEGORY":"Employee 0",
      "REVISION NUMBER":'5464',
      "QUANTITY":"4",
      "UOM":"ttd",
      "PROCUREMENT TYPE":"each",
      "UNIT COST":"6",
      "TOTAL COST":"6",
      "CURRENCY ":"us",
      "START DATE":"12/08/2018",
      "END DATE":"15/08/2018",
      "PART TYPE":"product",
      "YIELD":"5",
      "PLANNING PERCENTAGE":"56",
      "CUSTOM ATTRIBUTES ":"",
         "childs":[  
         {
           "SEQUENCE NUMBER":2.1,
           "OPERATIONAL SEQUENCE ":"P4828",
           "COMPONENT NUMBER":"Employee1",
           "COMPONENT NAME":"Director of IT",
           "ITEM CATEGORY":"Employee 0",
           "REVISION NUMBER":'',
           "QUANTITY":"",
           "UOM":"",
           "PROCUREMENT TYPE":"",
           "UNIT COST":"",
           "TOTAL COST":"",
           "CURRENCY ":"",
           "START DATE":"",
           "END DATE":"",
           "PART TYPE":"",
           "YIELD":"",
           "PLANNING PERCENTAGE":"",
           "CUSTOM ATTRIBUTES ":"",
    
         },
         {
           "SEQUENCE NUMBER":2.2,
           "OPERATIONAL SEQUENCE ":"P4828",
           "COMPONENT NUMBER":"Employee1",
           "COMPONENT NAME":"Director of IT",
           "ITEM CATEGORY":"Employee 0",
           "REVISION NUMBER":'5464',
           "QUANTITY":"4",
           "UOM":"ttd",
           "PROCUREMENT TYPE":"each",
           "UNIT COST":"6",
           "TOTAL COST":"6",
           "CURRENCY ":"us",
           "START DATE":"12/08/2018",
           "END DATE":"15/08/2018",
           "PART TYPE":"product",
           "YIELD":"5",
           "PLANNING PERCENTAGE":"56",
           "CUSTOM ATTRIBUTES ":"",
         }
        ]
    },
    {
      "SEQUENCE NUMBER":3,
      "OPERATIONAL SEQUENCE ":"P4828",
      "COMPONENT NUMBER":"Employee1",
      "COMPONENT NAME":"Director of IT",
      "ITEM CATEGORY":"Employee 0",
      "REVISION NUMBER":'5464',
      "QUANTITY":"4",
      "UOM":"ttd",
      "PROCUREMENT TYPE":"each",
      "UNIT COST":"6",
      "TOTAL COST":"6",
      "CURRENCY ":"us",
      "START DATE":"12/08/2018",
      "END DATE":"15/08/2018",
      "PART TYPE":"product",
      "YIELD":"5",
      "PLANNING PERCENTAGE":"56",
      "CUSTOM ATTRIBUTES ":"",
      
      "childs":[  
         {
           "SEQUENCE NUMBER":3.1,
           "OPERATIONAL SEQUENCE ":"P4828",
           "COMPONENT NUMBER":"Employee1",
           "COMPONENT NAME":"Director of IT",
           "ITEM CATEGORY":"Employee 0",
           "REVISION NUMBER":'',
           "QUANTITY":"",
           "UOM":"",
           "PROCUREMENT TYPE":"",
           "UNIT COST":"",
           "TOTAL COST":"",
           "CURRENCY ":"",
           "START DATE":"",
           "END DATE":"",
           "PART TYPE":"",
           "YIELD":"",
           "PLANNING PERCENTAGE":"",
           "CUSTOM ATTRIBUTES ":"",
           "childs":[  
            {
              "SEQUENCE NUMBER":'3.1.1',
              "OPERATIONAL SEQUENCE ":"P4828",
              "COMPONENT NUMBER":"Employee1",
              "COMPONENT NAME":"Director of IT",
              "ITEM CATEGORY":"Employee 0",
              "REVISION NUMBER":'',
              "QUANTITY":"",
              "UOM":"",
              "PROCUREMENT TYPE":"",
              "UNIT COST":"",
              "TOTAL COST":"",
              "CURRENCY ":"",
              "START DATE":"",
              "END DATE":"",
              "PART TYPE":"",
              "YIELD":"",
              "PLANNING PERCENTAGE":"",
              "CUSTOM ATTRIBUTES ":"",
       
            },
            {
              "SEQUENCE NUMBER":'3.1.2',
              "OPERATIONAL SEQUENCE ":"P4828",
              "COMPONENT NUMBER":"Employee1",
              "COMPONENT NAME":"Director of IT",
              "ITEM CATEGORY":"Employee 0",
              "REVISION NUMBER":'5464',
              "QUANTITY":"4",
              "UOM":"ttd",
              "PROCUREMENT TYPE":"each",
              "UNIT COST":"6",
              "TOTAL COST":"6",
              "CURRENCY ":"us",
              "START DATE":"12/08/2018",
              "END DATE":"15/08/2018",
              "PART TYPE":"product",
              "YIELD":"5",
              "PLANNING PERCENTAGE":"56",
              "CUSTOM ATTRIBUTES ":"",
            }
           ]
         },
         {
           "SEQUENCE NUMBER":3.2,
           "OPERATIONAL SEQUENCE ":"P4828",
           "COMPONENT NUMBER":"Employee1",
           "COMPONENT NAME":"Director of IT",
           "ITEM CATEGORY":"Employee 0",
           "REVISION NUMBER":'5464',
           "QUANTITY":"4",
           "UOM":"ttd",
           "PROCUREMENT TYPE":"each",
           "UNIT COST":"6",
           "TOTAL COST":"6",
           "CURRENCY ":"us",
           "START DATE":"12/08/2018",
           "END DATE":"15/08/2018",
           "PART TYPE":"product",
           "YIELD":"5",
           "PLANNING PERCENTAGE":"56",
           "CUSTOM ATTRIBUTES ":"",
         }
        ]
       
    }
 ];
}